#!/usr/bin/env bash
#
# add-cluster.sh — (re)generates one cluster's Caddy site blocks under
# clusters.d/, for the multi-cluster VPS edge (PLAN.md §7D,
# docs/vps-edge-deployment.md). Run once per independent private cluster
# this VPS proxy fans out to — e.g. once for domain1.com's cluster, again
# for domain2.com's — each reachable over its own WireGuard tunnel peer
# (setup-wireguard.sh --role vps --peer-name <id> ...).
#
# Unlike the single-cluster Caddyfile this replaced, domain/upstream
# values are baked as literals into clusters.d/<id>.caddy rather than
# read from environment variables at `caddy run` time — with N
# independent clusters there's no single $ADMIN_DOMAIN/$MGMT_UPSTREAM to
# share, and env vars can't be scoped per import file. Same reasoning as
# setup-wireguard.sh's peers.d/ pattern: re-running this script for one
# cluster only ever touches that cluster's own file.

set -euo pipefail

PROG="$(basename "$0")"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLUSTERS_DIR="$SCRIPT_DIR/clusters.d"

ID=""
ADMIN_DOMAIN=""
API_DOMAIN=""
PLAY_DOMAIN=""
MGMT_UPSTREAM=""
PORTAL_ROOT=""

usage() {
  cat <<EOF
Usage: $PROG --id <cluster-id> --admin-domain <fqdn> --api-domain <fqdn> \\
             --play-domain <fqdn> --mgmt-upstream <host:port> \\
             [--portal-root <path>]

Required:
  --id ID               Short identifier for this cluster (letters/digits/
                           -/_ only — matches folia-nexa-proxy's
                           FOLIA_MGMT_CLUSTER_IDS entries, see
                           FoliaRoutesSyncPlugin's javadoc). Determines the
                           output filename: clusters.d/<id>.caddy.
  --admin-domain FQDN   Public hostname for this cluster's mgmt dashboard,
                           e.g. admin.domain1.com
  --api-domain FQDN     Public hostname for this cluster's public API,
                           e.g. api.domain1.com
  --play-domain FQDN    Public hostname players use for the static portal
                           AND the hostname they type into their Minecraft
                           client (the latter never touches Caddy — see
                           the Caddyfile's own comment — but DNS for it
                           still needs to point here). e.g. play.domain1.com
  --mgmt-upstream HOST:PORT
                        This cluster's own mgmt, reachable over its own
                          WireGuard tunnel peer, e.g. 10.66.0.2:8443

Options:
  --portal-root PATH   Where this cluster's portal/ files live on this VPS
                          (default: /srv/folianexa-portal/<id> — pass the
                          matching --remote-root to deploy-portal.sh)
  -h, --help            Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --id) ID="$2"; shift 2 ;;
    --admin-domain) ADMIN_DOMAIN="$2"; shift 2 ;;
    --api-domain) API_DOMAIN="$2"; shift 2 ;;
    --play-domain) PLAY_DOMAIN="$2"; shift 2 ;;
    --mgmt-upstream) MGMT_UPSTREAM="$2"; shift 2 ;;
    --portal-root) PORTAL_ROOT="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1 (see --help)" >&2; exit 1 ;;
  esac
done

for var in ID ADMIN_DOMAIN API_DOMAIN PLAY_DOMAIN MGMT_UPSTREAM; do
  if [[ -z "${!var}" ]]; then
    echo "ERROR: --$(echo "$var" | tr '[:upper:]' '[:lower:]' | tr '_' '-') is required (see --help)" >&2
    exit 1
  fi
done

if [[ ! "$ID" =~ ^[a-zA-Z0-9_-]+$ ]]; then
  echo "ERROR: --id must contain only letters, digits, '-' or '_' (got '$ID')" >&2
  exit 1
fi

if [[ -z "$PORTAL_ROOT" ]]; then
  PORTAL_ROOT="/srv/folianexa-portal/$ID"
fi

mkdir -p "$CLUSTERS_DIR"
OUT="$CLUSTERS_DIR/$ID.caddy"

cat > "$OUT" <<EOF
# Cluster '$ID' — generated by add-cluster.sh. Re-run the script with
# updated values to regenerate this one file; other clusters' files
# under clusters.d/ are untouched either way.

$ADMIN_DOMAIN {
	# mgmt's own dashboard/API, unchanged — still behind its existing
	# bearer-token auth (PLAN.md §11A). mgmt itself never terminates TLS
	# (see docs/vps-edge-deployment.md); WireGuard already encrypts this
	# hop, so plain HTTP to the tunnel address is the deliberate choice
	# here, not an oversight.
	reverse_proxy $MGMT_UPSTREAM
}

$API_DOMAIN {
	# Only this cluster's unauthenticated /api/v1/public/* routes are
	# reachable through this hostname, even though its mgmt would
	# happily serve anything else too — defense in depth. The real auth
	# boundary is still that mgmt's own bearer-token check on every
	# non-public route.
	@public path /api/v1/public/*
	handle @public {
		reverse_proxy $MGMT_UPSTREAM
	}
	handle {
		respond 404
	}
}

$PLAY_DOMAIN {
	# The static player-hub portal (portal/) for THIS cluster — no
	# backend process here at all, just files (deploy-portal.sh
	# --remote-root $PORTAL_ROOT). portal/'s own JS derives its API base
	# from window.location.hostname (play.* -> api.*), so as long as
	# each cluster's play/api domains share the same base domain this
	# needs no extra config.
	root * $PORTAL_ROOT
	file_server
	encode gzip
}
EOF

echo "==> Wrote $OUT"
echo "==> Next: sudo caddy validate --config Caddyfile --adapter caddyfile && sudo systemctl reload caddy"
